/**
 * Generated by C-Next Transpiler from: actuator.cnx
 * A safer C for embedded systems
 */

#include "actuator.hpp"

#include <Arduino.h>

/* Scope: Actuator */

void Actuator_Initialize(void) {
    Serial.println("Actuator (C-Next) initialized");
}

void Actuator_Loop(void) {
}
