/**
 * Generated by C-Next Transpiler from: actuator.cnx
 * A safer C for embedded systems
 */

#include "actuator.hpp"

#include <Arduino.h>
#include "FlexCAN_T4.h"
#include "AppData.h"
#include "VaneConfig.h"

#include <stdint.h>

/* Scope: Actuator */
static FlexCAN_T4<CAN3,RX_SIZE_256,TX_SIZE_16> Actuator_canBus = {};

static void Actuator_receiveCallbackISR(const CAN_message_t& msg) {
    if (msg.id != 0x4EB) {
        return;
    }
    uint16_t rawPosition = 0;
    rawPosition = (uint16_t)((rawPosition & ~(0xFFU << 8)) | ((msg.buf[2U] & 0xFFU) << 8));
    rawPosition = (uint16_t)((rawPosition & ~(0xFFU << 0)) | ((msg.buf[3U] & 0xFFU) << 0));
    uint16_t motorLoad = 0;
    motorLoad = (uint16_t)((motorLoad & ~(0xFFU << 8)) | ((msg.buf[6U] & 0xFFU) << 8));
    motorLoad = (uint16_t)((motorLoad & ~(0xFFU << 0)) | ((msg.buf[7U] & 0xFFU) << 0));
    uint32_t raw = rawPosition;
    uint32_t mapped = raw * 100U / 1000U;
    uint32_t reported = 100U - mapped;
    appData.actuatorRawPosition = rawPosition;
    appData.actuatorMotorLoad = motorLoad;
    appData.actuatorStatus = msg.buf[0U];
    appData.actuatorTemp = msg.buf[5U];
    appData.actuatorReportedPosition = ((reported) & 0xFFU);
}

static uint8_t Actuator_positionToCommand(uint8_t position) {
    uint32_t pos = position;
    uint32_t inverted = 100U - pos;
    uint32_t command = inverted * 250U / 100U;
    return ((command) & 0xFFU);
}

void Actuator_Initialize(void) {
    Actuator_canBus.begin();
    Actuator_canBus.setBaudRate(500000);
    Actuator_canBus.setMaxMB(16);
    Actuator_canBus.enableFIFO();
    Actuator_canBus.enableFIFOInterrupt();
    Actuator_canBus.onReceive(Actuator_receiveCallbackISR);
    Actuator_canBus.mailboxStatus();
    Serial.println("Actuator (C-Next) initialized");
}

void Actuator_Loop(void) {
    uint8_t demanded = appData.actuatorDemandedPosition;
    if (demanded > VANE_OPEN_PERCENT) {
        demanded = VANE_OPEN_PERCENT;
    }
    CAN_message_t msg = {};
    msg.id = 0x4EA;
    msg.flags.extended = 0;
    msg.len = 8U;
    for (uint8_t i = 0; i < 8; i += 1) {
        msg.buf[i] = 0U;
    }
    msg.buf[0] = Actuator_positionToCommand(demanded);
    Actuator_canBus.write(msg);
}
