/**
 * Generated by C-Next Transpiler from: can_tx_queue.cnx
 * A safer C for embedded systems
 */

#include "can_tx_queue.hpp"

// Single-producer/single-consumer ring buffer of vane-position bytes.
// Producer = timer ISR (enqueue); consumer = main loop (dequeue).
// Arduino.h is required because critical {} expands to noInterrupts() on
// Arduino/ARM targets (ADR-050 portable IRQ wrappers).
#include <Arduino.h>

#include <stdint.h>
#include <stdbool.h>

// ADR-050: Platform-portable IRQ wrappers for critical sections
#if defined(__arm__) || defined(__ARM_ARCH)
// ARM platforms (including ARM Arduino like Teensy 4.x, Due, Zero)
// Provide inline assembly PRIMASK access to avoid CMSIS header dependencies
__attribute__((always_inline)) static inline uint32_t __cnx_get_PRIMASK(void) {
    uint32_t result;
    __asm volatile ("MRS %0, primask" : "=r" (result));
    return result;
}
__attribute__((always_inline)) static inline void __cnx_set_PRIMASK(uint32_t mask) {
    __asm volatile ("MSR primask, %0" :: "r" (mask) : "memory");
}
#if defined(ARDUINO)
static inline void __cnx_disable_irq(void) { noInterrupts(); }
#else
__attribute__((always_inline)) static inline void __cnx_disable_irq(void) {
    __asm volatile ("cpsid i" ::: "memory");
}
#endif
#elif defined(__AVR__)
// AVR Arduino: use SREG for interrupt state
// Note: Uses PRIMASK naming for API consistency across platforms (AVR has no PRIMASK)
// Returns uint8_t which is implicitly widened to uint32_t at call sites - this is intentional
static inline uint8_t __cnx_get_PRIMASK(void) { return SREG; }
static inline void __cnx_set_PRIMASK(uint8_t mask) { SREG = mask; }
static inline void __cnx_disable_irq(void) { cli(); }
#else
// Fallback: assume CMSIS is available
static inline void __cnx_disable_irq(void) { __disable_irq(); }
static inline uint32_t __cnx_get_PRIMASK(void) { return __get_PRIMASK(); }
static inline void __cnx_set_PRIMASK(uint32_t mask) { __set_PRIMASK(mask); }
#endif

/* Scope: CanTxQueue */
static uint8_t CanTxQueue_positions[8] = {0};
static uint8_t CanTxQueue_head = 0U;
static uint8_t CanTxQueue_tail = 0U;

void CanTxQueue_reset(void) {
    CanTxQueue_head = 0U;
    CanTxQueue_tail = 0U;
}

bool CanTxQueue_enqueue(uint8_t position) {
    uint8_t next = (CanTxQueue_head + 1U) & 7;
    bool full = (next == CanTxQueue_tail);
    if (full == true) {
        return false;
    }
    CanTxQueue_positions[CanTxQueue_head] = position;
    CanTxQueue_head = next;
    return true;
}

bool CanTxQueue_dequeue(uint8_t& outPosition) {
    bool empty = (CanTxQueue_head == CanTxQueue_tail);
    if (empty == true) {
        return false;
    }
    {
        uint32_t __primask = __cnx_get_PRIMASK();
        __cnx_disable_irq();
        outPosition = CanTxQueue_positions[CanTxQueue_tail];
        CanTxQueue_tail = (CanTxQueue_tail + 1U) & 7;
        __cnx_set_PRIMASK(__primask);
    }
    return true;
}
