#ifndef ACTUATOR_H
#define ACTUATOR_H

/**
 * Generated by C-Next Transpiler from: actuator.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "can_tx_queue.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void Actuator_Initialize(void);
void Actuator_Loop(void);

#ifdef __cplusplus
}
#endif

#endif /* ACTUATOR_H */
