#ifndef CAN_TX_QUEUE_H
#define CAN_TX_QUEUE_H

/**
 * Generated by C-Next Transpiler from: can_tx_queue.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void CanTxQueue_reset(void);
bool CanTxQueue_enqueue(uint8_t position);
bool CanTxQueue_dequeue(uint8_t& outPosition);

#ifdef __cplusplus
}
#endif

#endif /* CAN_TX_QUEUE_H */
