#ifndef JSON_H
#define JSON_H

/**
 * Generated by C-Next Transpiler from: json.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void Json_putByte(uint8_t c);
void Json_putRaw(const char* s);
void Json_putUintRaw(uint32_t v);
void Json_key(const char* k);
void Json_begin(void);
void Json_addUint(const char* k, uint32_t v);
void Json_addInt(const char* k, int32_t v);
void Json_addBool(const char* k, bool v);
void Json_addStr(const char* k, const char* v);
void Json_addFloat2(const char* k, float v);
void Json_end(void);
uint8_t Json_at(uint32_t i);
uint32_t Json_len(void);
bool Json_overflowed(void);

#ifdef __cplusplus
}
#endif

#endif /* JSON_H */
