#ifndef SYSTEMHEALTH_H
#define SYSTEMHEALTH_H

/**
 * Generated by C-Next Transpiler from: systemHealth.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "systemHealthLogic.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void SystemHealth_enableWatchdog(void);
void SystemHealth_init(void);
void SystemHealth_feed(void);
void SystemHealth_sampleSupply(void);
void SystemHealth_windowReset(void);
uint8_t SystemHealth_resetCauseCode(void);
uint32_t SystemHealth_bootCount(void);
uint32_t SystemHealth_loopMicrosMax(void);
uint32_t SystemHealth_loopMicrosAvg(void);
int32_t SystemHealth_supplyMillivolts(void);

#ifdef __cplusplus
}
#endif

#endif /* SYSTEMHEALTH_H */
