#ifndef SYSTEMHEALTHLOGIC_H
#define SYSTEMHEALTHLOGIC_H

/**
 * Generated by C-Next Transpiler from: systemHealthLogic.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint8_t SystemHealthLogic_decodeResetCause(uint32_t srsr);
void SystemHealthLogic_loopTimingReset(void);
void SystemHealthLogic_loopTimingRecord(uint32_t intervalMicros);
uint32_t SystemHealthLogic_loopTimingMax(void);
uint32_t SystemHealthLogic_loopTimingAvg(void);
uint32_t SystemHealthLogic_rawToMillivolts(uint32_t rawAdc);
void SystemHealthLogic_vinReset(void);
void SystemHealthLogic_vinRecord(uint32_t rawAdc);
int32_t SystemHealthLogic_vinMinMillivolts(void);

#ifdef __cplusplus
}
#endif

#endif /* SYSTEMHEALTHLOGIC_H */
